---
title: "related_work"
output:
  format: 
    latex:
params:
  eval_models: false
  
knitr:
  opts_chunk: 
    cache_comments: false
    crop: true
    
execute: 
  echo: false
  warning: false
  message: false
  include: false     
---

# Data Visualisation: A Brief History {#brief-history}

Data visualisation, which can be thought of as the practice representing information 
in a visual modality \cite{hinterberger_2009}, is difficult to concretely define,
classify, and categorise. With the primacy of vision with regards to our interactions with
and interpretations of the world around us, data visualisation may be thought of
as an extension of art and the written word. Both art and writing are ancient 
phenomena

# Measuring Relatedness {#measuring-relatedness}

# Conceptions of Correlation {#conceptions-of-correlation}

# Visualising Correlation {#visualising-correlation}

## History {#history-corr-viz}

## Present Landscape {#present-landscape-corr-viz}

## Scatterplots {#scatterplots-corr-viz}

# Correlation Perception {#corr-percept-related-work}

# Correlation Cognition {#corr-cognition}

# Underestimation: What's Really Going On? {#underestimation-whats-going-on}

# Underestimation: Potential Consequences {#underestimation-consequences}

# Data Visualisation Literacy {#graph-literacy-related-work}

# Objectives and Contributions {#objectives-contributions}
