---
title: "general_methodology"
output:
  format: 
    latex:
params:
  eval_models: false
  
knitr:
  opts_chunk: 
    cache_comments: false
    crop: true
    
execute: 
  echo: false
  warning: false
  message: false
  include: false     
---

# Introduction

In this chapter we describe our research methodologies. Chapters 4, 5, and 6 share
most aspects of experimental method, while the experiment described in chapter 7 differs
substantially. Throughout this chapter, the reader should assume that we are 
referring to the entire body of experimental work this thesis describes. Methods
that differ regarding the final experiment in chapter 7 are detailed along the way.
In this chapter, we discuss our experimental designs, the tools we use to build
and run our experiments, our approach to statistical analyses, and the computational
methods and practices we employed particularly with regards to reproducibility
and open science.

# Experimental Methods

## Experimental Design

## Tools for Testing

## Creating Stimuli

## Recruitment

# Analytical Methods

## Linear Mixed-Effects Models

## Advantages Over Aggregate-Level Statistical Tests

## Model Construction

## Effects Sizes

## Reporting Analyses

# Computational Methods

## Executable Reporting

## Containerised Environments

# Reproducibility In This Thesis

## Sharing Data and Code

## Executable Papers and Docker Containers

## Experimental Resources

# Conclusion
