---
title: "adjusting_opacity"
output:
  format: 
    latex:
params:
  eval_models: false
  
knitr:
  opts_chunk: 
    cache_comments: false
    crop: true
    
execute: 
  echo: false
  warning: false
  message: false
  include: false     
---

# Abstract {#abstract-adjusting-opacity}

# Preface: Learning From an Early Pilot Study {#pilot-study}

# Introduction {#introduction-adjusting-opacity}

## Overview {#overview-adjusting-opacity}

# Related Work {#related-work-adjusting-opacity}

## Transparency, Contrast, Opacity, and Formal Definitions

## Effects of Point Opacity on Correlation Estimation

# Experiment 1: Uniform Opacity Adjustments

## Introduction {#introduction-adjusting-opacity-e1}

## Methods {#methods-adjusting-opacity-e1}

## Analysis {#analysis-adjusting-opacity-e1}

## Discussion {#discussion-adjusting-opacity-e1}

# Experiment 2: Spatially-Dependent Opacity Adjustments

## Introduction {#introduction-adjusting-opacity-e2}

## Methods {#methods-adjusting-opacity-e2}

## Analysis {#analysis-adjusting-opacity-e2}

## Discussion {#discussion-adjusting-opacity-e2}

# General Discussion {#general-discussion-adjusting-opacity}
