---
title: "general_methodology"

output:
  format: 
    latex:

params:
  eval_models: false
  
knitr:
  opts_chunk: 
    cache_comments: false
    crop: true
    
execute: 
  echo: false
  warning: false
  message: false
  include: false     
---

# Introduction

As researchers, the selection of appropriate methods is crucial in order that our interpretations may be based in truth. The selection of methods necessarily
entails research of its own, with approaches each having distinct advantages and disadvantages, and thus the decisions that were made are discussed below. It is worth noting that 
different methods may produce different results, meaning this thesis cannot claim to be an entire representation of knowledge, but rather a reflection of the researcher, the ways
the research was done, and the particular philisophical environment that fostered the work.

# Experimental Methods

In order to understand how changing visual and design features can affect interpretations of scatterplots, the work presented here tests hypotheses using controlled experiments. This allows
for the isolation of factors of interest from other features, and allows us to establish causality with regards to effects. The use of empirical studies in visualisation has a rich
history \cite{lam_2012}, and facilitates the move towards designing from the ground up based on theory, as opposed to a more traditional paradigm in which visualisations are only tested
after they have been designed by technical experts.

## Experimental Design

\chap{chap:introduction}

## Tools for Testing

## Creating Stimuli

## Recruitment

# Analytical Methods

## Linear Mixed-Effects Models

## Advantages Over Aggregate-Level Statistical Tests

## Model Construction

## Effects Sizes

## Reporting Analyses

# Computational Methods

## Executable Reporting

## Containerised Environments

# Reproducility In This Thesis

## Sharing Data and Code

## Executable Papers and Docker Containers

## Experimental Resources

# Conclusion